### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by stone100010** [JonasOuellet/vscode-zscript#14]

**Comment by stone100010** [comment]
// Export All Number
[VarDef, ExportAllNumber, 5]




[Loop, 
	 ExportAllNumber, 
	 // command
	 // %4 = 
	 [If, 
	 	 ExportAllNumber_log < 4, 
	 	 // true
	 	 [Loop, 
	 	 	 // loop add "0" about allCLASS :42
	 	 	 42, 
	 	 	 [Note, ExportAllNumber_log], 
	 	 	 // [VarSet, zero_list, [StrMerge, zero_list, "0"]], 
	 	 	 log_str_0
	 	 ]
	 	 [Note, zero_list] , 
	 	 // false
	 	 [Note, "now ExportAllNumber_log is bigger than 4"]
	 	 [Note, ExportAllNumber_log]
	 ]
	 // command
	 , 
	 ExportAllNumber_log
]

**Comment by JonasOuellet** [comment]
Hello, there is an issue with having comments between [RoutineDef, and the routineName. I will fix it as soon as a can. Thx for flagging this issue.
