### ISSUE TITLE
Support for Additional Syntax Highlighting

### ISSUE THREAD

**Issue by BradHB3D** [JonasOuellet/vscode-zscript#9]
Fantastic start on this extension, thank you! I wonder what you think about adding support for additional syntax highlighting.. For example: local variables, memory block commands, other command types, etc are colored differently for at a glance recognition? here is an example:
[http://bradfolio.com/downloads/notepad-download-zscript-language/](url)

**Comment by JonasOuellet** [comment]
started working on syntax highlight, what do you think of this.

This is probably the most I can do without creating a custom color theme for vs code (which I don't really want).

![image](https://user-images.githubusercontent.com/10328303/88010897-f715a800-cae3-11ea-9d1c-990e6a3a580d.png)

**Comment by BradHB3D** [comment]
Excellent Jonas! This extension has been life-saver and is consolidating my development in VS Code! Thanks so much for all your effort

**Comment by JonasOuellet** [comment]
I'm glab to ear that :) The new syntax highlight is on the marketplace, you should be able to update to version 1.6.0.
